---
# tasks file for nginx
- name: Create NGINX container
  docker_container:
    name: nginx
    image: tanyaharutyunyan / nginx-github-actions:{{ image_tag }}
    recreate: yes
    ports:
      - "80:80"
    restart: yes
    restart_policy: always