---
# tasks file for nginx
- name: Create Nginx container
  docker_container:
    name: node_exporter
    image: tanyaharutyunyan/nginx-github-actions:{{ image_tag }}
    recreate: yes
    ports:
      - "80:80"
    restart: yes
    restart_policy: always